FROM microsoft/dotnet:2.2-aspnetcore-runtime-alpine3.8 AS base
WORKDIR /app

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY HelloWorldApi.csproj .
RUN dotnet restore "HelloWorldApi.csproj"
COPY . .

RUN dotnet build "HelloWorldApi.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "HelloWorldApi.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .

# IMPORTANT:
ENV ASPNETCORE_URLS http://+:5000

ENTRYPOINT ["dotnet", "HelloWorldApi.dll"]